// Routing paths
const Path = {
  SIGNUP: '/sign-up',
  LOGIN: '/login',
  HOME: '/',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  USERLIST: '/user-list',
  TRANSACTION_HISTORY: '/transaction-hisory',
  NFT_TRANSACTIONS: '/nft-transactions',
  SETTINGS: '/dashboard',
  FORGOTPASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  OTP: '/otp',
  USERDETAIL: '/user-detail',
  REWARD_REQUEST: '/reward-request',
  REWARD_HISTORY: '/reward-history',
  REWARD_CRITERIA: '/reward-criteria',
  TOKEN_LISTING: '/token-listing',
  PUSH_NOTIFICATIONS: '/push-notifications',
  PUSH_NOTIFICATIONS_HISTORY: '/push-notifications-history',
  SEND_USERS: '/send-users',
  NOTIFICATION_PREVIEW: '/notifications-PREVIEW',
  BANNER_NOTIFICATIONS: '/banner-notifications',
  UPLOAD_BANNER_PREVIEW: '/upload-banner-preview',
  BLOCKCHAIN_STATUS: '/block-chain-status',
  SUB_ADMIN: '/sub-admin',
  USER_ACCESS: '/user-access',
  // ACTIVITY_LOGS: "/activity-logs",
  SETTING: '/setting',
  ROLE_MANAGEMENT: '/role-management',
};

export default Path;
